version: '3'
services:
  api:
    build: ./evento-api    # Referência à pasta do back-end
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: yourpassword
      DB_NAME: eventos
      JWT_SECRET: your_jwt_secret
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: eventos
    ports:
      - "3306:3306"

  frontend:
    build: ./evento-frontend  # Referência à pasta do front-end
    ports:
      - "3001:3000"
